package rw.gov.sacco.stockmis.v1.enums;

public enum EPORequestStatus {
    PENDING,
    APPROVER_APPROVAL,
    DIRECTOR_GENERAL_APPROVAL,
    DIRECTOR_GENERAL_REJECTION,
    APPROVER_REJECTION,
    PROC_MANAGER_APPROVAL,
    PROC_MANAGER_REJECTION,
    DELETED
}
