package rw.gov.sacco.stockmis.v1.enums;

public enum ERequestStatus {
    PENDING, APPROVER_APPROVAL, APPROVER_REJECTION, STORE_KEEPER_APPROVAL, STORE_KEEPER_REJECTION,
    HOHR_APPROVAL, HOHR_REJECTION, APPROVED, APPEAL, REJECTED, GRANTED
}
